plugins { id 'com.android.application' }
android {
 namespace 'com.whalehunter.ai'
 compileSdk 35
 defaultConfig {
  applicationId 'com.whalehunter.ai.v7'
  minSdk 23
  targetSdk 35
  versionCode 7
  versionName '7.0'
 }
 buildTypes {
  release {
   signingConfig signingConfigs.debug
   minifyEnabled false
  }
 }
}
