plugins { id 'com.android.application' }
android {
 namespace 'com.whalehunter.ai'
 compileSdk 36
 defaultConfig {
  applicationId 'com.whalehunter.ai.final'
  minSdk 23
  targetSdk 36
  versionCode 21
  versionName '21.0'
 }
 buildTypes {
  release {
   signingConfig signingConfigs.debug
   minifyEnabled false
  }
 }
}