export function buildMasterSignal(scan){
  const market=scan.market||{};
  const whale=scan.whale||{};
  const best=market.bestPair||{};
  const acc24=Array.isArray(whale.accumulating24h)?whale.accumulating24h:[];
  const acc7=Array.isArray(whale.accumulating7d)?whale.accumulating7d:[];
  const confirmedBuys=Array.isArray(whale.confirmedDexBuys24h)?whale.confirmedDexBuys24h:[];
  const independent=Array.isArray(whale.independentWhales)?whale.independentWhales:[];
  const evidence=Number(scan.evidence?.score||0);
  const dexConfirmed=Boolean(scan.evidence?.confirmedDexBuyActivity);
  const liquidity=Number(best.liquidityUsd||0);
  const buys=Number(best.buys24h||0);
  const sells=Number(best.sells24h||0);
  const risks=[];
  if(!scan.dataQuality?.holderDiscoveryConfigured)risks.push("HOLDER_DATA_MISSING");
  if(liquidity<25000)risks.push("LOW_LIQUIDITY");
  if(sells>buys)risks.push("SELL_PRESSURE");
  if(!dexConfirmed)risks.push("NO_MARKET_BUY_CONFIRMATION");
  if(acc24.length===0)risks.push("NO_24H_WHALE_NET_INFLOW");
  if(confirmedBuys.length===0)risks.push("NO_WHALE_DEX_BUY_CONFIRMATION");
  const confirmations=[];
  if(dexConfirmed)confirmations.push("DEX_BUY_ACTIVITY");
  if(confirmedBuys.length>0)confirmations.push("WHALE_DEX_BUY_CONFIRMED");
  if(acc24.length>=3)confirmations.push("MULTIPLE_WHALES_NET_INFLOW_24H");
  if(acc7.length>=3)confirmations.push("MULTIPLE_WHALES_NET_INFLOW_7D");
  if(independent.length>=10)confirmations.push("BROAD_INDEPENDENT_HOLDER_BASE");
  if(liquidity>=100000)confirmations.push("HEALTHY_LIQUIDITY");
  let state="INSUFFICIENT_EVIDENCE";
  if(evidence>=70&&confirmedBuys.length>=2&&confirmations.length>=3&&risks.length<=1)state="STRONG_EVIDENCE";
  else if(evidence>=45&&confirmedBuys.length>=1&&confirmations.length>=2&&risks.length<=2)state="WATCH";
  else if(evidence>=25)state="MIXED_EVIDENCE";
  return {state,evidenceScore:evidence,confirmedWhaleBuys24h:confirmedBuys.length,confirmations,risks,note:"Evidence strength is not a probability of a future pump and is not investment advice."};
}
