export const AGENTS=[
{id:"marketScanner",name:"Market Scanner",icon:"🌐"},
{id:"whaleHunter",name:"Whale Hunter",icon:"🐋"},
{id:"independentWhaleFilter",name:"Independent Whale Filter",icon:"🛡️"},
{id:"dexBuyDetector",name:"DEX Buy Detector",icon:"💱"},
{id:"cexFlow",name:"CEX Flow",icon:"🏦"},
{id:"accumulation",name:"Accumulation Detector",icon:"📈"},
{id:"whaleNetwork",name:"Whale Network",icon:"🕸️"},
{id:"technical",name:"Technical",icon:"📊"},
{id:"smartMoney",name:"Smart Money / Liquidity",icon:"💧"},
{id:"volume",name:"Volume",icon:"📶"},
{id:"liquidity",name:"Liquidity",icon:"🌊"},
{id:"tokenomics",name:"Tokenomics",icon:"🪙"},
{id:"security",name:"Contract / Security",icon:"🔐"},
{id:"newToken",name:"New Token",icon:"🆕"},
{id:"earlyAccumulation",name:"Early Accumulation",icon:"🚀"},
{id:"pumpPattern",name:"Pump Pattern",icon:"⚡"},
{id:"distribution",name:"Distribution",icon:"📤"},
{id:"sentiment",name:"Sentiment",icon:"💬"},
{id:"futures",name:"Futures",icon:"📉"},
{id:"marketRegime",name:"Market Regime",icon:"🧭"},
{id:"falseSignal",name:"False Signal",icon:"⚠️"},
{id:"master",name:"Master Agent",icon:"🧠"}
];